export const ADD_TODAYS_TODO = "ADD_TODAYS_TODO";
export const COMPLETE_TODAYS_TODO = "COMPLETE_TODAYS_TODO";
export const RESET_TO_NOT_COMPLETED_TODAYS_TODO = "RESET_TO_NOT_COMPLETED_TODAYS_TODO";
export const DELETE_TODAYS_TODO = "DELETE_TODAYS_TODO";

export const COMPLETE_TRIED_TODO = "COMPLETE_TRIED_TODO";
export const RESET_TO_NOT_COMPLETED_TRIED_TODO = "RESET_TO_NOT_COMPLETED_TRIED_TODO";
